# Blueprint for Render deployment
services:
  # Web Service
  - type: web
    name: fire-ems-tools
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: fire-ems-db
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: RENDER
        value: "true"
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /

# Database
databases:
  - name: fire-ems-db
    databaseName: fire_ems
    user: fire_ems_user
    plan: standard