# Blueprint for Render deployment
services:
  # Web Service
  - type: web
    name: fire-ems-tools
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && chmod +x ./build_simple.sh && ./build_simple.sh
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: NODE_VERSION
        value: 18.20.0
      - key: DATABASE_URL
        fromDatabase:
          name: fire-ems-db
          property: connectionString
      - key: SQLALCHEMY_TRACK_MODIFICATIONS
        value: "False"
      - key: REDIS_URL
        fromService:
          type: redis
          name: fire-ems-redis
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: RENDER
        value: "true"
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /

# Database
databases:
  - name: fire-ems-db
    databaseName: fire_ems
    user: fire_ems_user
    plan: standard

# Redis
services:
  - type: redis
    name: fire-ems-redis
    ipAllowList: # required
      - source: 0.0.0.0/0
        description: everywhere
    plan: free # optional (defaults to starter)
    maxmemoryPolicy: volatile-lru # optional (defaults to allkeys-lru)