name: Fire-EMS Tools CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  simplified-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-mock coverage
        
    - name: Run simplified tests
      run: python run_all_tests.py --category simplified

    - name: Run error tests
      run: python run_all_tests.py --category error

    - name: Run boundary tests
      run: python run_all_tests.py --category boundary
      
  coverage-analysis:
    runs-on: ubuntu-latest
    needs: simplified-tests
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install coverage pytest pytest-mock
        
    - name: Run coverage analysis
      run: |
        chmod +x ./run_coverage.py
        ./run_coverage.py --categories all --html --xml
        
    - name: Upload coverage reports
      uses: actions/upload-artifact@v3
      with:
        name: coverage-reports
        path: coverage_reports/latest/
        retention-days: 14

  e2e-tests:
    runs-on: ubuntu-latest
    needs: simplified-tests
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Install Playwright
      working-directory: ./e2e
      run: |
        npm ci
        npx playwright install --with-deps chromium
        
    - name: Run E2E tests
      working-directory: ./e2e
      run: |
        npm test -- --project=chromium --grep-invert "Security Testing"
      env:
        BASE_URL: http://localhost:8080
        
    - name: Upload Playwright report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: playwright-report
        path: e2e/test-results
        retention-days: 30
        
  security-tests:
    runs-on: ubuntu-latest
    needs: e2e-tests
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Install security scanning tools
      run: |
        python -m pip install bandit safety
        
    - name: Run Python security scan
      run: |
        bandit -r . -x ./tests,./e2e,./venv
        safety check
        
    - name: Install Playwright
      working-directory: ./e2e
      run: |
        npm ci
        npx playwright install --with-deps chromium
        
    - name: Run Security E2E tests
      working-directory: ./e2e
      run: |
        npm test -- --project=chromium --grep "Security Testing"
      env:
        BASE_URL: http://localhost:8080
        
    - name: Upload Security test report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: security-test-report
        path: e2e/test-results
        retention-days: 30